### PR TITLE
Style_tone_tags file creation & indexation

### PR DESCRIPTION
**Pull request by LTLucieOld**
Creation and indexation of file Style ToneTags.
This file:
- documents how to add the feature tone_tags= to style rules.
- lists all ToneTags
- lists all Writing Goals
- explains the mapping between them

### CODE REVIEW

**Comment by LTLucieOld** [comment]
Hi Daniel, 
It's my first attempt at writing a new file in this repo. I've tried to mimic what was done for the other files, but i'm not sure it's complete. 
Thanks a lot for your patience and review here!

**Comment by danielnaber** [comment]
Now online at https://dev.languagetool.org/style_tone_tags, but the table doesn't render... not sure why.

**Comment by LTLucieOld** [comment]
mmh, weird, it looked perfect in the IntelliJ preview

**Comment by LTLucieOld** [comment]
Pedro (thanks!) amazingly fixed the tables and improved the page.

**Pull request merged**
