### PR TITLE
Update Homebrew instructions

### PR DESCRIPTION
**Pull request by moabits**
Revert changes by @escapedcat. If there is trouble with the brew service it should be reported in https://github.com/Homebrew/homebrew-core. The service works for practically all people.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, but please see https://github.com/languagetool-org/languagetool-org.github.io/pull/21 - this change contradicts the change from a few days ago.

**Comment by moabits** [comment]
The service runs the [same command](https://github.com/Homebrew/homebrew-core/blob/45e2dc62226726bc0fa76871ee1f4878b984d79d/Formula/l/languagetool.rb#L55), this must be an individual error by the user or could be related to this [fixed issue](https://github.com/Homebrew/homebrew-core/pull/161125).

**Comment by escapedcat** [comment]
Thanks everybody. Will check again!

Update: Works!

**Comment by moabits** [comment]
> Update: Works!

 @danielnaber Then let's get this merged.

**Pull request merged**
